[versions]
agp = "9.1.0"
kotlin = "2.2.10"
ksp = "2.3.6"
hilt = "2.59.2"
coroutines = "1.10.2"
androidXAnotation = "1.9.1"
material = "1.13.0"
androidXCore = "1.18.0"
appCompat = "1.7.1"
androidXActivityKtx = "1.13.0"
constraintLayout = "2.2.1"
recyclerView = "1.4.0"
playServicesNearby = "19.3.0"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidXAnotation" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidXCore" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidx-activityKtx = { module = "androidx.activity:activity-ktx", version.ref = "androidXActivityKtx" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
androidx-recyclerView = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltCompiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
play-services-nearby = { group = "com.google.android.gms", name = "play-services-nearby", version.ref = "playServicesNearby" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
android-application = { id = "com.android.application" }
